settings:
  title: 'Status Page'
  url: 'https://status.eplus.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: eplus-dev # unique identifier
    name: eplus.dev
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://eplus.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: radio-eplus-dev  # unique identifier
    name: radio.eplus.dev
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://radio.eplus.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: uptime-eplus-dev # unique identifier
    name: uptime.eplus.dev
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://uptime.eplus.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: hub-eplus-dev # unique identifier
    name: hub.eplus.dev
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://hub.eplus.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: forum-eplus-dev # unique identifier
    name: forum.eplus.dev
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://forum.eplus.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: blog-eplus-dev # unique identifier
    name: blog.eplus.dev
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://blog.eplus.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: tools-eplus-dev # unique identifier
    name: tools.eplus.dev
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://tools.eplus.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true




